auth:
  username: "18330179404"
  password: "bigben100"
  url: "http://v2.yituike.com/index/login/indexlogin"
receivers:
  - name: "拼多多互砍~201"
    link: "http://拼多多互砍~201.com"
    skipImage: false
  - name: "bigben"
    link: "http://拼多多互砍~201.com"
    skipImage: true
  - name: "拼多多互砍~201"
    link: "http://拼多多互砍~201.com"
    skipImage: false
fanli:
  refreshInterval: 20
  sendInterval: 1
  process:
    url: "http://v2.yituike.com/admin/goods/goods_store?limit=100&page=1&state=1"
    start: false
    msgPrefix: "这是进行中的消息前缀"
  premonitor:
    url: "http://v2.yituike.com/admin/goods/goods_store?limit=100&page=1&state=2"
    start: true
    msgPrefix: "这是预告的消息前缀"