auth:
  username: "18330179404"
  password: "bigben100"
  url: "http://v2.yituike.com/index/login/login"
receiver:
  - name: "拼多多互砍~201"
    link: "http://拼多多互砍~201.com"
    skipimage: false
  - name: "bigben"
    link: "http://拼多多互砍~201.com"
    skipimage: false
  - name: "拼多多互砍~201"
    link: "http://拼多多互砍~201.com"
    skipimage: false
fanli:
  refreshinterval: 20
  sendinterval: 1
  process:
    url: "http://v2.yituike.com/admin/goods/goods_store?limit=100&page=1&state=1"
    start: false
  premonitor:
    url: "http://v2.yituike.com/admin/goods/goods_store?limit=100&page=1&state=2"
    start: true